version: "3.9"
services:
  api-server: 
    build: ./api-server
    ports:
      - 5000:5000
  
  database:
    image: mongo
    ports:
      - 27017:27017
  
  wappalyzer:
    build: ./wappalyzer
    ports:
      - 3000:3000
      - 3001:3001
    depends_on: 
      - database
      - api-server